---
# Commitlint configuration
# https://commitlint.js.org/
#
# Install: npm install -g @commitlint/cli @commitlint/config-conventional
# Test: echo "feat: add feature" | commitlint

extends:
  - "@commitlint/config-conventional"

rules:
  # Type must be one of the following
  type-enum:
    - 2  # Error level
    - always
    - - feat      # New feature
      - fix       # Bug fix
      - docs      # Documentation changes
      - style     # Formatting, whitespace (no code change)
      - refactor  # Code restructuring (no behavior change)
      - perf      # Performance improvement
      - test      # Adding or updating tests
      - build     # Build system or dependencies
      - ci        # CI/CD configuration
      - chore     # Maintenance tasks
      - revert    # Revert a previous commit

  # Type must be lowercase
  type-case:
    - 2
    - always
    - lower-case

  # Subject must not be empty
  subject-empty:
    - 2
    - never

  # Subject must not end with period
  subject-full-stop:
    - 2
    - never
    - "."

  # Subject max length
  subject-max-length:
    - 2
    - always
    - 72

  # Header max length (type + scope + subject)
  header-max-length:
    - 2
    - always
    - 100

  # Body max line length
  body-max-line-length:
    - 1  # Warning level
    - always
    - 120

  # Footer max line length
  footer-max-line-length:
    - 1
    - always
    - 120

  # Scope is optional but must be lowercase if provided
  scope-case:
    - 2
    - always
    - lower-case
